# Generated by Django 5.2 on 2025-04-26 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('brand', 'Brand'), ('influencer', 'Influencer'), ('user', 'User')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('social_media_links', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True)),
                ('open_to_work', models.BooleanField(default=False)),
                ('can_receive_gifts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
