# Generated by Django 5.2 on 2025-05-07 13:52

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_image_original',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.banner_image_original_path, verbose_name='Original Banner Image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_image_processing',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_original',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_picture_original_path, verbose_name='Original Profile Picture'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_processing',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.banner_image_resized_path, verbose_name='Banner Image (Resized)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_picture_resized_path, verbose_name='Profile Picture (Resized)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('brand', 'Brand'), ('influencer', 'Influencer'), ('user', 'User')], max_length=20, null=True),
        ),
    ]
